require("dotenv").config();
const express=require("express"),cors=require("cors"),helmet=require("helmet"),rateLimit=require("express-rate-limit"),http=require("http"),{Server}=require("socket.io"),webpush=require("web-push"),db=require("./db"),{sign,auth}=require("./auth");
const app=express();
const server=http.createServer(app);
const corsOrigin=process.env.CORS_ORIGIN?process.env.CORS_ORIGIN.split(',').map(x=>x.trim()):true;
app.use(helmet({crossOriginResourcePolicy:{policy:"cross-origin"}}));
app.use(cors({origin:corsOrigin,credentials:true}));
app.use(express.json({limit:"200kb"}));
app.use(rateLimit({windowMs:15*60*1000,limit:300,standardHeaders:true,legacyHeaders:false}));
const io=new Server(server,{cors:{origin:corsOrigin,methods:["GET","POST","PATCH"]}});
const pushReady=!!(process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY&&process.env.VAPID_SUBJECT);
if(pushReady) webpush.setVapidDetails(process.env.VAPID_SUBJECT,process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);
function notifyUser(userId,event,payload){io.to(`user:${userId}`).emit(event,payload);if(pushReady){const sub=db.prepare("SELECT subscription_json FROM push_subscriptions WHERE user_id=?").get(userId);if(sub)webpush.sendNotification(JSON.parse(sub.subscription_json),JSON.stringify({event,...payload})).catch(()=>{});}}
io.use((socket,next)=>{try{const token=socket.handshake.auth?.token;if(!token)return next(new Error("AUTH_REQUIRED"));const jwt=require("jsonwebtoken");const p=jwt.verify(token,process.env.JWT_SECRET||"dev-secret");socket.userId=p.id;socket.role=p.role;next()}catch(e){next(new Error("INVALID_TOKEN"))}});
io.on("connection",socket=>{socket.join(`user:${socket.userId}`);socket.emit("connected",{ok:true});});
const otp=new Map(), otpAttempts=new Map(), PRICE={base:50,perKm:25,min:80};
async function sendOtpSms(phone,code){
 if(process.env.OTP_MODE==="demo") return true;
 if(process.env.SMS_PROVIDER==="twilio" && process.env.TWILIO_ACCOUNT_SID && process.env.TWILIO_AUTH_TOKEN && process.env.TWILIO_FROM){
  const body=new URLSearchParams({To:phone,From:process.env.TWILIO_FROM,Body:`کد ورود میزاری آنلاین: ${code}`});
  const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${process.env.TWILIO_ACCOUNT_SID}/Messages.json`,{method:"POST",headers:{Authorization:"Basic "+Buffer.from(process.env.TWILIO_ACCOUNT_SID+":"+process.env.TWILIO_AUTH_TOKEN).toString("base64"),"Content-Type":"application/x-www-form-urlencoded"},body});
  if(!r.ok) throw new Error("SMS_SEND_FAILED"); return true;
 }
 console.warn("SMS provider is not configured"); return false;
}

const valid=p=>/^07\d{8}$/.test(String(p||""));
const ride=id=>db.prepare("SELECT * FROM rides WHERE id=?").get(id);
function km(a,b,c,d){if([a,b,c,d].some(x=>typeof x!=="number"))return Infinity;const R=6371,p1=a*Math.PI/180,p2=c*Math.PI/180,dp=(c-a)*Math.PI/180,dl=(d-b)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
app.get("/api/health",(q,s)=>s.json({ok:true,service:"mizari-online",time:new Date().toISOString()}));

app.post("/api/auth/request-otp",(q,s)=>{let p=String(q.body.phone||"");if(!valid(p))return s.status(400).json({error:"INVALID_PHONE"});const now=Date.now(), last=otp.get(p);if(last&&last.sentAt&&now-last.sentAt<60000)return s.status(429).json({error:"OTP_COOLDOWN"});let code=String(Math.floor(100000+Math.random()*900000));if(process.env.OTP_MODE==="demo")code="123456";otp.set(p,{code,until:Date.now()+300000,sentAt:Date.now()});otpAttempts.set(p,0);
sendOtpSms(p,code).then(()=>s.json({ok:true,demoCode:process.env.OTP_MODE==="demo"?code:undefined})).catch(()=>s.status(502).json({error:"OTP_DELIVERY_FAILED"}));});
app.post("/api/auth/verify-otp",(q,s)=>{let p=String(q.body.phone||""),c=String(q.body.code||""),o=otp.get(p);let attempts=otpAttempts.get(p)||0;if(!valid(p)||!o||o.until<Date.now()||attempts>=5)return s.status(400).json({error:"INVALID_OTP"});if(o.code!==c){otpAttempts.set(p,attempts+1);return s.status(400).json({error:"INVALID_OTP"});}let u=db.prepare("SELECT * FROM users WHERE phone=?").get(p);if(!u){let role=p===process.env.ADMIN_PHONE?"admin":"passenger";let r=db.prepare("INSERT INTO users(phone,role) VALUES(?,?)").run(p,role);u=db.prepare("SELECT * FROM users WHERE id=?").get(r.lastInsertRowid)}otp.delete(p);s.json({token:sign(u),user:u})});
app.get("/api/me",auth(),(q,s)=>s.json({user:q.user,driver:db.prepare("SELECT * FROM drivers WHERE user_id=?").get(q.user.id)||null}));
app.get("/api/push/public-key",(q,s)=>s.json({enabled:pushReady,publicKey:process.env.VAPID_PUBLIC_KEY||null}));
app.post("/api/push/subscribe",auth(),(q,s)=>{if(!q.body.subscription)return s.status(400).json({error:"SUBSCRIPTION_REQUIRED"});db.prepare("INSERT INTO push_subscriptions(user_id,subscription_json,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_id) DO UPDATE SET subscription_json=excluded.subscription_json,updated_at=CURRENT_TIMESTAMP").run(q.user.id,JSON.stringify(q.body.subscription));s.json({ok:true,enabled:pushReady})});

app.patch("/api/me",auth(),(q,s)=>{db.prepare("UPDATE users SET name=? WHERE id=?").run(String(q.body.name||"").slice(0,100),q.user.id);s.json({user:db.prepare("SELECT * FROM users WHERE id=?").get(q.user.id)})});

app.post("/api/drivers/register",auth(["passenger","driver"]), (q,s)=>{if(db.prepare("SELECT id FROM drivers WHERE user_id=?").get(q.user.id))return s.status(409).json({error:"DRIVER_EXISTS"});let b=q.body,r=db.prepare("INSERT INTO drivers(user_id,vehicle_type,vehicle_model,vehicle_color,plate) VALUES(?,?,?,?,?)").run(q.user.id,b.vehicleType||"sedan",b.vehicleModel||"",b.vehicleColor||"",b.plate||"");db.prepare("UPDATE users SET role='driver' WHERE id=?").run(q.user.id);s.status(201).json({driver:db.prepare("SELECT * FROM drivers WHERE id=?").get(r.lastInsertRowid)})});
app.post("/api/drivers/verify/:id",auth(["admin"]),(q,s)=>{db.prepare("UPDATE drivers SET verified=? WHERE id=?").run(q.body.verified?1:0,q.params.id);s.json({ok:true})});
app.get("/api/admin/drivers",auth(["admin"]),(q,s)=>s.json({drivers:db.prepare("SELECT d.*,u.phone,u.name FROM drivers d JOIN users u ON u.id=d.user_id ORDER BY d.id DESC").all()}));
app.post("/api/drivers/status",auth(["driver"]), (q,s)=>{let d=db.prepare("SELECT * FROM drivers WHERE user_id=?").get(q.user.id);if(!d)return s.status(404).json({error:"DRIVER_NOT_FOUND"});let lat=Number(q.body.lat),lng=Number(q.body.lng);db.prepare("UPDATE drivers SET online=?,lat=?,lng=? WHERE id=?").run(q.body.online?1:0,Number.isFinite(lat)?lat:d.lat,Number.isFinite(lng)?lng:d.lng,d.id);s.json({driver:db.prepare("SELECT * FROM drivers WHERE id=?").get(d.id)})});
app.get("/api/drivers/nearby",auth(),(q,s)=>{let lat=Number(q.query.lat),lng=Number(q.query.lng),max=Number(q.query.maxKm||10);let ds=db.prepare("SELECT d.*,u.name,u.phone FROM drivers d JOIN users u ON u.id=d.user_id WHERE d.online=1 AND d.verified=1 AND d.lat IS NOT NULL AND d.lng IS NOT NULL").all().map(d=>({...d,distanceKm:km(lat,lng,d.lat,d.lng)})).filter(d=>d.distanceKm<=max).sort((a,b)=>a.distanceKm-b.distanceKm);s.json({drivers:ds})});

app.post("/api/rides",auth(["passenger"]), (q,s)=>{let b=q.body;if(!b.originText||!b.destinationText)return s.status(400).json({error:"ORIGIN_DESTINATION_REQUIRED"});let d=Math.max(0,Number(b.distanceKm||0)),t=Math.max(0,Number(b.durationMin||0)),fare=Math.max(PRICE.min,PRICE.base+d*PRICE.perKm),r=db.prepare(`INSERT INTO rides(passenger_id,origin_text,destination_text,origin_lat,origin_lng,destination_lat,destination_lng,distance_km,duration_min,fare,payment_method,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(q.user.id,b.originText,b.destinationText,Number(b.originLat)||null,Number(b.originLng)||null,Number(b.destinationLat)||null,Number(b.destinationLng)||null,d,t,fare,b.paymentMethod||"cash","searching");const created=ride(r.lastInsertRowid);notifyUser(q.user.id,"ride:update",{ride:created});s.status(201).json({ride:created})});
app.get("/api/rides",auth(),(q,s)=>{if(q.user.role==="admin")return s.json({rides:db.prepare("SELECT * FROM rides ORDER BY id DESC LIMIT 500").all()});if(q.user.role==="passenger")return s.json({rides:db.prepare("SELECT * FROM rides WHERE passenger_id=? ORDER BY id DESC").all(q.user.id)});let d=db.prepare("SELECT id FROM drivers WHERE user_id=?").get(q.user.id);s.json({rides:d?db.prepare("SELECT * FROM rides WHERE driver_id=? ORDER BY id DESC").all(d.id):[]})});
app.get("/api/rides/:id",auth(),(q,s)=>{let r=ride(q.params.id);if(!r)return s.status(404).json({error:"RIDE_NOT_FOUND"});let d=r.driver_id&&db.prepare("SELECT user_id FROM drivers WHERE id=?").get(r.driver_id);if(q.user.role!=="admin"&&r.passenger_id!==q.user.id&&(!d||d.user_id!==q.user.id))return s.status(403).json({error:"FORBIDDEN"});s.json({ride:r})});

app.post("/api/rides/:id/accept",auth(["driver"]), (q,s)=>{let d=db.prepare("SELECT * FROM drivers WHERE user_id=?").get(q.user.id);if(!d||!d.online||!d.verified)return s.status(400).json({error:"DRIVER_NOT_AVAILABLE"});const tx=db.transaction(()=>{let r=ride(q.params.id);if(!r||r.status!=="searching")return null;let x=db.prepare("UPDATE rides SET driver_id=?,status='driver_assigned',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='searching' AND driver_id IS NULL").run(d.id,r.id);return x.changes?ride(r.id):null});let r=tx();if(!r)return s.status(409).json({error:"RIDE_ALREADY_TAKEN"});notifyUser(r.passenger_id,"ride:update",{ride:r});notifyUser(q.user.id,"ride:update",{ride:r});s.json({ride:r})});

const transitions={driver_assigned:["driver_arrived","cancelled"],driver_arrived:["trip_started","cancelled"],trip_started:["completed","cancelled"],searching:["cancelled"]};
app.post("/api/rides/:id/status",auth(),(q,s)=>{let r=ride(q.params.id),n=String(q.body.status||"");if(!r)return s.status(404).json({error:"RIDE_NOT_FOUND"});if(!transitions[r.status]?.includes(n))return s.status(400).json({error:"INVALID_STATUS_TRANSITION"});db.prepare("UPDATE rides SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(n,r.id);if(n==="completed"&&r.driver_id)db.prepare("UPDATE drivers SET earnings=earnings+? WHERE id=?").run(r.fare,r.driver_id);const updated=ride(r.id);notifyUser(updated.passenger_id,"ride:update",{ride:updated});if(updated.driver_id){const du=db.prepare("SELECT user_id FROM drivers WHERE id=?").get(updated.driver_id);if(du)notifyUser(du.user_id,"ride:update",{ride:updated});}s.json({ride:updated})});
app.post("/api/rides/:id/rate",auth(),(q,s)=>{let r=ride(q.params.id),score=Number(q.body.score);if(!r||r.status!=="completed"||!Number.isInteger(score)||score<1||score>5)return s.status(400).json({error:"INVALID_RATING"});let du=r.driver_id&&db.prepare("SELECT user_id FROM drivers WHERE id=?").get(r.driver_id)?.user_id,to=q.user.id===r.passenger_id?du:r.passenger_id;if(!to)return s.status(400).json({error:"TARGET_NOT_FOUND"});try{db.prepare("INSERT INTO ratings(ride_id,from_user_id,to_user_id,score,comment) VALUES(?,?,?,?,?)").run(r.id,q.user.id,to,score,String(q.body.comment||"").slice(0,500))}catch{return s.status(409).json({error:"RATING_EXISTS"})}s.json({ok:true})});
app.get("/api/drivers/earnings",auth(["driver"]), (q,s)=>{let d=db.prepare("SELECT * FROM drivers WHERE user_id=?").get(q.user.id);s.json({earnings:d?.earnings||0,driver:d||null})});
app.post("/api/complaints",auth(),(q,s)=>{if(!q.body.message||!q.body.category)return s.status(400).json({error:"INVALID_COMPLAINT"});let r=db.prepare("INSERT INTO complaints(user_id,ride_id,category,message) VALUES(?,?,?,?)").run(q.user.id,q.body.rideId||null,q.body.category,q.body.message);s.status(201).json({complaint:db.prepare("SELECT * FROM complaints WHERE id=?").get(r.lastInsertRowid)})});
app.get("/api/admin/stats",auth(["admin"]),(q,s)=>s.json({users:db.prepare("SELECT count(*) c FROM users").get().c,drivers:db.prepare("SELECT count(*) c FROM drivers").get().c,onlineDrivers:db.prepare("SELECT count(*) c FROM drivers WHERE online=1").get().c,rides:db.prepare("SELECT count(*) c FROM rides").get().c,activeRides:db.prepare("SELECT count(*) c FROM rides WHERE status NOT IN ('completed','cancelled')").get().c,complaints:db.prepare("SELECT count(*) c FROM complaints WHERE status='open'").get().c}));
app.get("/api/admin/complaints",auth(["admin"]),(q,s)=>s.json({complaints:db.prepare("SELECT * FROM complaints ORDER BY id DESC").all()}));

server.listen(Number(process.env.PORT||3000),"0.0.0.0",()=>console.log("Mizari Online API on "+(process.env.PORT||3000)));